name: Build Flet APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install flet firebase-admin

      - name: Build APK
        run: |
          # Este comando crea el APK y lo guarda en la carpeta build/apk
          flet build apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: el-rincon-app-final
          path: build/apk/*.apk
          if-no-files-found: error
