name: Build Flet APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet & Firebase
        run: |
          pip install flet firebase-admin

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.0'

      - name: Pre-accept Android Licenses
        run: |
          # Esto acepta las licencias de Android antes de que Flet las pida
          yes | sdkmanager --licenses || true

      - name: Build APK (Modo Silencioso)
        run: |
          # Usamos un truco de terminal para forzar la respuesta 'y' a todo
          printf 'y\n' | flet build apk --no-interaction
