name: Build Flet APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install flet firebase-admin

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # Esto instala Flutter antes para que Flet no tenga que preguntar nada

      - name: Build APK
        run: |
          # El comando 'yes' le dice que sí a cualquier pregunta de la terminal
          yes | flet build apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: el-rincon-app-final
          path: build/apk/*.apk
          if-no-files-found: error
