name: Build Flet APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet & Firebase
        run: |
          pip install flet firebase-admin

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.0'

      - name: Pre-accept Android Licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Build APK (Manual Config)
        run: |
          # 1. Le decimos a Flet dónde está Flutter exactamente para que no pregunte
          flet config flutter_path $FLUTTER_HOME
          
          # 2. Ejecutamos el build con una entrada forzada 'y' por si acaso
          echo "y" | flet build apk --no-interaction
